apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
  namespace: argocd
spec:
  roles:
  # A role which provides access to all applications in the project
  - name: access
    #description: Read-only privileges to infra project
    description: privileges to infra project
    policies:
    - p, proj:infra:admin, applications, get, infra/*, allow
    - p, proj:infra:admin, repositories, update, infra/https://github.com/alokhom, allow
    - p, proj:infra:admin, repositories, create, infra/*, allow
    - p, proj:infra:admin, repositories, delete, infra/*, allow
    #- p, proj:infra:admin, repositories, update, infra*, allow
    groups:
    - my-oidc-group
  # sourceRepos:
  # - '*'
  # Do not use the test repo in argoproj
  #- '!ssh://git@GITHUB.com:argoproj/test'
  # Nor any Gitlab repo under group/ 
  #- '!https://gitlab.com/group/**'
  # Any other repo is fine though
  #- '*'
  #
  #
  # destinations:
  # - namespace: '*'
  #   server: '*'
  # Do not allow any app to be installed in `kube-system`  
  #- namespace: '!kube-system'
  #  server: '*'
  # Or any cluster that has a URL of `team1-*`   
  #- namespace: '*'
  #  server: '!https://team1-*'
    # Any other namespace or server is fine though.
  #- namespace: '*'
  #  server: '*'
  #
  #
  # clusterResourceWhitelist:
  # - group: '*'
  #   kind: '*'