---
# Source: drone-runner-docker/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: drone-docker-runner-drone-runner-docker
  namespace: oapp-dev
  labels:
    release: drone-docker-runner
    helm.sh/chart: drone-runner-docker-0.6.1
    app.kubernetes.io/name: drone-runner-docker
    app.kubernetes.io/instance: drone-docker-runner
    app.kubernetes.io/version: "1.8.1"
    app.kubernetes.io/managed-by: Helm
---
# Source: drone-runner-docker/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: drone-docker-runner-drone-runner-docker
  namespace: oapp-dev
  labels:
    release: drone-docker-runner
    helm.sh/chart: drone-runner-docker-0.6.1
    app.kubernetes.io/name: drone-runner-docker
    app.kubernetes.io/instance: drone-docker-runner
    app.kubernetes.io/version: "1.8.1"
    app.kubernetes.io/managed-by: Helm
data:
  DOCKER_HOST: "tcp://localhost:2375"
  # drone server serivce in oapp-dev namespace 
  DRONE_RPC_HOST: "drone"
  DRONE_RPC_PROTO: "http"
  DRONE_RPC_SECRET: "032744fbad892b1cd1957249d214a3fa"
---
# Source: drone-runner-docker/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: drone-docker-runner-drone-runner-docker
  namespace: oapp-dev
  labels:
    release: drone-docker-runner
    helm.sh/chart: drone-runner-docker-0.6.1
    app.kubernetes.io/name: drone-runner-docker
    app.kubernetes.io/instance: drone-docker-runner
    app.kubernetes.io/version: "1.8.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: drone-runner-docker
    app.kubernetes.io/instance: drone-docker-runner
---
# Source: drone-runner-docker/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-docker-runner-drone-runner-docker
  namespace: oapp-dev
  labels:
    release: drone-docker-runner
    helm.sh/chart: drone-runner-docker-0.6.1
    app.kubernetes.io/name: drone-runner-docker
    app.kubernetes.io/instance: drone-docker-runner
    app.kubernetes.io/version: "1.8.1"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: drone-runner-docker
      app.kubernetes.io/instance: drone-docker-runner
  template:
    metadata:
      labels:
        app.kubernetes.io/name: drone-runner-docker
        app.kubernetes.io/instance: drone-docker-runner
    spec:
      serviceAccountName: drone-docker-runner-drone-runner-docker
      securityContext:
        fsGroup: 1000900000
        #runAsNonRoot: true
        runAsUser: 1000900000
        runAsGroup: 10000
      containers:
        - name: dind
          image: "docker.io/docker:24.0.6-dind-rootless"
          imagePullPolicy: IfNotPresent
          command:
            - dockerd
          args:
            - --host
            - tcp://localhost:2375
          securityContext:
            #privileged: true
            # capabilities:
            #   drop:
            #    - ALL
            #   add: 
            #    - CAP_SYS_ADMIN 
            # runAsNonRoot: true
            runAsUser: 1000900000
            #allowPrivilegeEscalation: true
          livenessProbe:
            exec:
              command:
              - docker
              - -H 
              - tcp://localhost:2375
              - images
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            exec:
              command:
              - docker
              - -H 
              - tcp://localhost:2375
              - images
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - mountPath: /var/lib/docker
              name: storage
              subPath: docker
            - mountPath: /var/run/
              name: dind-socket
        - name: gc
          image: "docker.io/drone/gc:1.0.0"
          imagePullPolicy: IfNotPresent
          env:
            - name: DOCKER_HOST
              value: tcp://localhost:2375
            - name: GC_CACHE
              value: "5gb"
            - name: GC_DEBUG
              value: "false"
            - name: GC_DEBUG_COLOR
              value: "false"
            - name: GC_DEBUG_PRETTY
              value: "false"
            - name: GC_IGNORE_CONTAINERS
              value: ""
            - name: GC_IGNORE_IMAGES
              value: ""
            - name: GC_INTERVAL
              value: "5m"
        - name: drone-runner-docker
          securityContext:
            # capabilities:
            #   drop:
            #   - ALL
            # readOnlyRootFilesystem: true
            # runAsNonRoot: true
            runAsUser: 1000900000
          image: "docker.io/drone/drone-runner-docker:1.8.1"
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: drone-docker-runner-drone-runner-docker
          env:
            - name: DOCKER_HOST
              value: tcp://localhost:2375
            - name: DRONE_RUNNER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - name: tcp
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: tcp
          readinessProbe:
            tcpSocket:
              port: tcp
      volumes:
        - emptyDir: {}
          name: storage
        - name: dind-socket
          emptyDir: {}
---
# Source: drone-runner-docker/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: drone-docker-runner-drone-runner-docker
  namespace: oapp-dev
  labels:
    release: drone-docker-runner
    helm.sh/chart: drone-runner-docker-0.6.1
    app.kubernetes.io/name: drone-runner-docker
    app.kubernetes.io/instance: drone-docker-runner
    app.kubernetes.io/version: "1.8.1"
    app.kubernetes.io/managed-by: Helm
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: "docker-runer.apps.aro.az.acntech.no"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: drone-docker-runner-drone-runner-docker
                port:
                  number: 80
