---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: redhat-rhpds-gitea
  namespace: oapp-dev
spec:
  sourceType: grpc
  image: quay.io/rhpds/gitea-catalog:latest
  displayName: Red Hat Demo Platform (Gitea)
  publisher: Red Hat Demo Platform
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: gitea-operator
  namespace: oapp-dev
spec:
  targetNamespaces: []
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: gitea-operator
  namespace: oapp-dev
spec:
  channel: stable
  installPlanApproval: Automatic
  name: gitea-operator
  source: redhat-rhpds-gitea
  sourceNamespace: gitea-operator
