# Source: gitea/templates/gitea/pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitea-shared-storage
  namespace: oapp-dev
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: azure-file
  resources:
    requests:
      storage: 10Gi