apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  namespace: oapp-dev
type: Opaque
data:
  KEYCLOAK_ADMIN: YWRtaW4K
  KEYCLOAK_ADMIN_PASSWORD: b2FwcDEyMzQ=
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: keycloak
  name: keycloak
  namespace: oapp-dev
spec:
  podManagementPolicy: Parallel
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: keycloak
  serviceName: keycloak-headless
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: keycloak
        env:
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "admin"
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: KC_HEALTH_ENABLED
          value: "true"
        - name: KC_METRICS_ENABLED
          value: "true"
        - name: KC_HOSTNAME
          value: "keycloak.apps.aro.az.acntech.no"
        - name: KC_HOSTNAME_STRICT
          value: "false"
        - name: KC_HOSTNAME_STRICT_HTTPS
          value: "false"
        - name: KC_HTTP_ENABLED
          value: "true"
        # - name: KC_HTTP_RELATIVE_PATH
        #   value: "/auth"
        - name: KC_HOSTNAME_ADMIN_URL
          value: "https://keycloak.apps.aro.az.acntech.no/"
        - name: KC_TRANSACTION_XA_ENABLED
          value: "false"
        - name: KC_PROXY
          value: "edge"
        - name: KC_DB
          value: "postgres"
        - name: KC_DB_URL_HOST
          value: "gitea-postgresql"
        - name: KC_DB_URL_DATABASE
          #value: "keycloak"
          value: "postgres"
        - name: KC_DB_URL_PORT
          value: "5432"
        - name: KC_DB_SCHEMA
          #value: "keycloak"
          value: "public"
        - name: KC_DB_USERNAME
          value: "postgres"
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgres-password
              name: gitea-postgresql
        - name: jgroups.dns.query
          value: "keycloak"
        image: quay.io/keycloak/keycloak:22.0.0
        args: ["start-dev"]
        resources:
          requests:
            cpu: "1200m"
            memory: "1000Mi"
          limits:
            cpu: "1500m"
            memory: "1500Mi"
        imagePullPolicy: IfNotPresent
        securityContext:
          # capabilities:
          #   drop:
          #     - ALL
          # readOnlyRootFilesystem: true
          # runAsNonRoot: true
          runAsUser: 1000900000
        ports:
        - name: jgroups
          containerPort: 7600
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8443
          name: https
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /realms/master
            port: http
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /realms/master
            port: http
            scheme: HTTP
          initialDelaySeconds: 300
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: kc-pvc
      # volumes:
      # - name: kc-pvc
      #   emptyDir: {}
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: kc-pvc
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: standard
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: oapp-dev
  labels:
    app: keycloak
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: keycloak
  type: LoadBalancer